name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trivy-scan:
    uses: vmware-tanzu/carvel-release-scripts/.github/workflows/trivy-scan.yml@main
    with:
      repo: vmware-tanzu/carvel-kbld
      tool: kbld
      goVersion: 1.17.0
